### ISSUE TITLE
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>

### ISSUE THREAD

**Issue by Jimmy062006** [iraf-community/pyraf#131]
Every day at 3am the camera reports a firmware update (in the unifi controller) and never comes back online.

The below stack trace is the only thing I have been able to fine.

2022-03-12 19:31:22 0c697a21f66f RTSPCam[1] INFO Processing [GetSystemStats] message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/unifi/clock_sync.py", line 167, in <module>
    main()
  File "/app/unifi/clock_sync.py", line 157, in main
    write(read_bytes(source, payload_size))
  File "/app/unifi/clock_sync.py", line 87, in write
    sys.stdout.buffer.write(data)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
av_interleaved_write_frame(): Broken pipe
    Last message repeated 1 times
Error writing trailer of pipe:: Broken pipe

**Comment by olebole** [comment]
How is this connected to PyRAF?

**Comment by Jimmy062006** [comment]
To be fair I'd like to know how I got here as it wasn't the github I click new issue on lol.
