### ISSUE TITLE
Error while installing Pyraf

### ISSUE THREAD

**Issue by mrkendurkar** [iraf-community/pyraf#148]
Hello,

 I had to re-install iraf/pyraf and now it is giving me this error. 
```
pyraf
Traceback (most recent call last):
  File "/home/deneb/miniconda3/lib/python3.9/site-packages/pyraf/iraffunctions.py", line 155, in Init
    iraf = _os.environ['iraf']
  File "/home/deneb/miniconda3/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'iraf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deneb/miniconda3/lib/python3.9/site-packages/pyraf/iraffunctions.py", line 160, in Init
    d = _getIrafEnv()
  File "/home/deneb/miniconda3/lib/python3.9/site-packages/pyraf/iraffunctions.py", line 267, in _getIrafEnv
    raise OSError(f"CL startup file {file} does not exist")
OSError: CL startup file /usr/local/bin/cl does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deneb/miniconda3/bin/pyraf", line 8, in <module>
    sys.exit(main())
  File "/home/deneb/miniconda3/lib/python3.9/site-packages/pyraf/__main__.py", line 130, in main
    iraf.Init(**initkw)
  File "/home/deneb/miniconda3/lib/python3.9/site-packages/pyraf/iraffunctions.py", line 166, in Init
    raise OSError("""
OSError: 
Your "iraf" environment variable is not defined and could not be
determined from /usr/local/bin/cl.  This is are needed to find IRAF
tasks.  Before starting pyraf, define ot by doing (for example):

    export iraf=/iraf/iraf/

at the Unix command line. Actual values will depend on your IRAF installation,
and they are set during the IRAF user installation (see https://iraf-community.github.io).
Also be sure to run the "mkiraf" command to create a logion.cl
(http://www.google.com/search?q=mkiraf).
```
Thanks in advance

**Comment by olebole** [comment]
Is your **iraf** environment variable set as described in the error message?

**Comment by olebole** [comment]
Is this still relevant? Otherwise I would close it.
