### ISSUE TITLE
Installation of pyobjc breaks pyraf on a MacOS Sonoma (14.3) system

### ISSUE THREAD

**Issue by olebole** [iraf-community/pyraf#163]
Installation of pyobjc actually breaks pyraf on a MacOS Sonoma (14.3) system, i.e. `pip install pyraf` works but then doing a `pip install pyobj` causes the startup to fail with:

```
Traceback (most recent call last):
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple//bin/pyraf", line 8, in <module>
    sys.exit(main())
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/__main__.py", line 112, in main
    splash_screen = splash.splash(f'PyRAF {__version__}')
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/splash.py", line 219, in splash
    return IrafMonitorSplash(label, background=background, **kw)
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/splash.py", line 174, in __init__
    PyrafSplash.__init__(self, text=[None, label], **kw)
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/splash.py", line 92, in __init__
    wutil.forceFocusToNewWindow()
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/wutil.py", line 187, in forceFocusToNewWindow
    aqutil.focusOnGui()
  File "/Applications/PyRAF.app/Contents/pyraf-v2.2.1/miniconda3-apple/lib/python3.8/site-packages/pyraf/aqutil.py", line 38, in focusOnGui
    raise Exception("SetFrontProcess: " + str(err))
Exception: SetFrontProcess: -13066
```

The PyRAF.app in this case is a miniconda system, adding pyobjc leads to the above regardless of distribution.  See perhaps https://stackoverflow.com/questions/28442944/getprocessforpid-not-deprecated

_Originally posted by @mjfitzpatrick in https://github.com/iraf-community/pyraf/issues/156#issuecomment-1980999939_

**Comment by olebole** [comment]
The functions **GetCurrentProcess**, **GetFrontProcess** and **SetFrontProcess** are indeed Carbon functions and deprecated since ages. IMO, the handling via processes should be replaced with "apps"; namely
* **NSWorkspace.shared.frontmostApplication()** to get the app for the currently active process,
* **NSApp** or **NSApplication.sharedApplication()** to get the current application
*  ***app*.activate()** to bring ***app*** to front
* Checking whether an ***app*** is active can be done with the ***app*.isActive()** method.

All from googling around; I need to find access to a new Mac to implement/test this. If someone wants to hijack and implement: don't hesitate.
