### ISSUE TITLE
Obscure exception during first interpreter shutdown in Python 3

### ISSUE THREAD

**Issue by jehturner** [iraf-community/pyraf#61]
This seems to happen as the Python interpreter is shutting down, after being started without an existing cache. Apparently things are getting cleaned up in the wrong order or something. It's not a disaster for interactive use, but causes our regression tests to fail without producing any results. I started looking into this but hadn't got to the bottom of the problem and had better document it in the meantime. 
```
> rm -fr pyraf
> pyraf
Created directory /home/jturner/test/pyraf for cache
setting terminal type to xterm...

   NOAO/IRAF PC-IRAF Revision 2.16 EXPORT Thu May 24 15:41:17 MST 2012
      This is the EXPORT version of IRAF V2.16 supporting PC systems.


  Welcome to IRAF.  To list the available commands, type ? or ??.  To get
  detailed information about a command, type `help <command>'.  To run  a
  command  or  load  a  package,  type  its name.   Type  `bye' to exit a
  package, or `logout' to get out  of the CL.    Type `news' to find  out
  what is new in the version of the system you are using.  

  Visit http://iraf.net if you have questions or to report problems.

  The following commands or packages are currently defined:

  (Updated on 2013-12-13)

clpackage/:
 adccdrom/      esowfi/         mem0/           rvsao/          user/
 cfh12k/        finder/         mscdb/          softools/       utilities/
 cirred/        fitsutil/       mscred/         sqiid/          vo/
 clpackage/     gemini/         mtools/         stecf/          xdimsum/
 ctio/          gmisc/          nfextern/       stsdas/         xray/
 cutoutpkg/     guiapps/        noao/           system/
 dataio/        images/         obsolete/       tables/
 dbms/          language/       plot/           ucsclris/
 deitab/        lists/          proto/          upsqiid/
PyRAF 2.2.dev Copyright (c) 2002 AURA
Python 3.6.2 Copyright (c) 2001-2017 Python Software Foundation.
Python/CL command line wrapper
  .help describes executive commands
--> .exit
Exception ignored in: <bound method _CodeCache.__del__ of <pyraf.clcache._CodeCache object at 0x7f8a7f730860>>
Traceback (most recent call last):
  File "/home/jturner/anaconda2/envs/test3/lib/python3.6/site-packages/pyraf/clcache.py", line 193, in __del__
  File "/home/jturner/anaconda2/envs/test3/lib/python3.6/site-packages/pyraf/clcache.py", line 184, in close
  File "/home/jturner/anaconda2/envs/test3/lib/python3.6/shelve.py", line 144, in close
  File "/home/jturner/anaconda2/envs/test3/lib/python3.6/shelve.py", line 172, in sync
  File "/home/jturner/anaconda2/envs/test3/lib/python3.6/dbm/dumb.py", line 121, in _commit
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method _Database.close of <dbm.dumb._Database object at 0x7f8a7f7309e8>>
Traceback (most recent call last):
  File "/home/jturner/anaconda2/envs/test3/lib/python3.6/dbm/dumb.py", line 279, in close
  File "/home/jturner/anaconda2/envs/test3/lib/python3.6/dbm/dumb.py", line 121, in _commit
TypeError: 'NoneType' object is not callable
```

**Comment by olebole** [comment]
Since this does not appear after switching to sqlshelve, I am closing this issue.

**Comment by jehturner** [comment]
That's good news, as I think this was stopping us running our usual tests properly. I'll try to confirm (I've had a few hiccups trying to get a good test installation).

**Comment by jehturner** [comment]
Yes, I'm no longer seeing this and can run our Gemini IRAF tests, thanks.

**Comment by olebole** [comment]
Thank you for testing!
